### PR TITLE
Update ember-cli to 2.4.2

### PR DESCRIPTION
**Pull request by mattmcmanus**
A build of mine was failing because of the version of htmlbars that was being used in this plugin. Not quite sure why that happened. In the process of updating it, I ended up just doing a whole project update to ember-cli 2.4.2. 

Nearly everything that changed was boilerplate that was updated by `ember init`. The only tweaking happened in `bower.json` and `package.json`.

### CODE REVIEW

**Comment by broerse** [comment]
This looks good. Can test with my app this weekend.

**Comment by lazybensch** [comment]
This Looks great, will have a closer look later today

Thanks

**Comment by lazybensch** [comment]
merged this in @mattmcmanus, thx again! I will wait for the weekend to see if @broerse finds any issues, if not i will bump the addon version then.

**Comment by mattmcmanus** [comment]
Hooray. Glad to help. Thanks!

**Comment by broerse** [comment]
@mattmcmanus @lazybensch tested already. No issues found. Thanks!

**Pull request merged**
